{% set name = "aiofiles" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a1c4fc9b2ff81568c83e21392a82f344ea9d23da906e4f6a52662764545e19d4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4

test:
  imports:
    - aiofiles

about:
  home: https://github.com/Tinche/aiofiles
  summary: File support for asyncio
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - kszucs
    - carlodri
