{% set name = "aiofiles" %}
{% set version = "0.5.0" %}
{% set sha256 = "98e6bcfd1b50f97db4980e182ddd509b7cc35909e903a8fe50d8849e02d815af" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4

test:
  imports:
    - aiofiles

about:
  home: https://github.com/Tinche/aiofiles
  summary: File support for asyncio
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - kszucs
    - carlodri
